export const CharlasData = [
    {id: 1,
     titulo: " Amplifying Impact: ",
     texto: "El poder de la Influencia y el Empoderamiento: En esta charla transformadora, desbloquearemos los secretos de la influencia y el empoderamiento que pueden llevar el impacto de tu empresa a niveles inimaginables. Exploraremos cómo la influencia puede convertirse en una poderosa herramienta para inspirar, motivar y conectar con tu equipo y clientes internos y externos. Descubrirás cómo influir de manera auténtica y significativa, creando relaciones duraderas que trascienden cualquier barrera.",
     textoOtro: "Pero eso no es todo, en esta charla también te mostraremos cómo el empoderamiento puede desencadenar una ola de potencial y creatividad en tu empresa. Aprenderás cómo cultivar una cultura de confianza y autonomía, permitiendo que tus empleados brillen en su máximo esplendor. No se trata solo de teoría, sino de aplicar la magia en la vida real. Te proporcionaremos herramientas concretas para implementar el cambio en tu empresa y medir el impacto que estás generando en el negocio."
    },
    {id: 2,
        titulo: " Datewithmyself, turismo interior:  ",
     texto: "Pocas veces invertimos tiempo en nosotros mismos. Muchas veces reemplazamos externamente espacios de autoconocimiento que si bien, son más que válidos, ¿qué sucede con el poder de descubrirnos? ¿Alguna vez tomamos un café con nosotros mismos?.",
     textoOtro: "El autoconocimiento proporciona estabilidad y equilibrio, logrando grandes resultados dentro y fuera de la compañía en la que trabaja la persona. En esta experiencia transformadora, os invitaremos a emprender un viaje hacia vuestro interior, descubriendo el poder y el potencial que reside dentro de cada persona. Datewithmyself es un viaje de autodescubrimiento y crecimiento personal, un turismo interior que llevará a tus empleados a lugares que nunca imaginaste. Datewithmyself también es un turismo interior hacia la autenticidad, ser genuino con nosotros y con los otros. Este viaje hacia tu interior no termina en la conferencia, es el comienzo de una transformación continua en la vida diarias de las personas. Proporcionaremos herramientas reales para que las personas puedan sseguir explorando y creciendo por si mismo/a. Si una persona está conectada con su esencia y está sentada en la “silla correcta”, está comprobado que mejora su rendimiento y esto impactará fuertemente en vuestro negocio."
   
       }, 
    {id: 3,
        titulo: "Construyendo un Legado:",
     texto: "Liderazgo Transformador en Tiempos de Incertidumbre: Hoy la incertidumbre laboral no solamente es algo racional, sino que tiene un gran impacto emocional en las personas. Aprender a gestionar a las personas con alegría, generando sensaciones que los impulsen a seguir mejorando, aún en tiempos de incertidumbre. Aprender a ser un buen líder dentro de la cultura organizacional, y así impulsar de la mejor manera a su equipo para obtener el mayor rendimiento posible. El líder es el resorte que debe lidear con las exigencias de toda la pirámide organizacional, por ello, hay que escucharlos, cuidarlos, contenerlos y ayudarlos en su gestión.En tiempos inciertos, el liderazgo transformador es la brújula que guiará a tu equipo y a tu empresa hacia la grandeza. Exploraremos cómo los líderes excepcionales son capaces de inspirar a otros y forjar un camino hacia el éxito incluso en las circunstancias más difíciles. En esta charla, aprenderán estrategias prácticas y tácticas probadas para liderar con claridad, visión y empatía. Trabajaremos mucho el concepto de “Liquidez en el trabajo”.",
     textoOtro: "Proporcionaremos herramientas para fomentar la resiliencia en los equipos y adaptación al cambio y flexibilidad de manera efectiva. Exploraremos cómo los líderes transformadores pueden aprovechar la innovación y la creatividad para encontrar oportunidades en medio de la incertidumbre. Descubrirán cómo construir una cultura organizacional sólida que promueva la colaboración y el trabajo en equipo."
   
       }, 
       {id: 5,
        titulo: "Sinfonía:",
        texto: "Todas las generaciones armonizadas en nuestra organización: como conviven tantas generaciones en una misma organización sin perder el control de administrar correctamente a cada persona. Esta charla tiene como objetivo explorar y abordar la importancia de la diversidad generacional en el entorno laboral. Durante esta charla, se destacará cómo aprovechar las diferencias generacionales para construir una cultura empresarial inclusiva y exitosa. Los participantes aprenderán sobre las características y preferencias únicas de cada generación presente en la fuerza laboral, como Baby Boomers, Generación X, Millennials y Generación Z. Se explorará cómo estas diferencias pueden complementarse y enriquecerse mutuamente para crear un ambiente de trabajo armonioso y productivo. Los asistentes aprenderán cómo fomentar la colaboración intergeneracional y promover una cultura de respeto y entendimiento mutuo. Se proporcionarán estrategias prácticas para facilitar la comunicación efectiva entre diferentes generaciones y superar posibles conflictos o malentendidos.",
        textoOtro:"En este espacio se destacará la importancia de reconocer y valorar las diversas habilidades y experiencias que cada generación aporta a la organización. Se resaltarán casos de éxito de empresas que han abrazado la diversidad generacional y han cosechado beneficios significativos en términos de innovación, creatividad y retención de talento. Además, se explorará cómo la inclusión generacional puede mejorar el compromiso y la satisfacción de los empleados, lo que a su vez impacta positivamente en la productividad y el rendimiento de la empresa."
    },
    
    {id: 6,
        titulo: "Camino incierto, destino brillante:",
        texto: "La Magia de Emprender en la incertidumbre : Durante esta charla, se abordarán diversos temas y estrategias para ayudar a los emprendedores y/o empleados de una organización a navegar con éxito por situaciones inciertas y crear negocios resilientes y exitosos. En esta conferencia, los asistentes aprenderán a desarrollar una mentalidad positiva y resiliente que les permita enfrentar los obstáculos con confianza y creatividad. Se compartirán historias inspiradoras de emprendedores que han superado adversidades y han logrado éxito en tiempos de incertidumbre, sirviendo como fuente de inspiración y motivación. Flexibilidad será uno de los conceptos más poderosos de la misma.",
        textoOtro:"Los participantes también aprenderán a identificar oportunidades emergentes en medio de la incertidumbre y a aprovechar la innovación como una poderosa herramienta para encontrar soluciones disruptivas. Se explorarán estrategias para adaptar el modelo de negocio y las estrategias en un entorno cambiante, y se brindarán consejos prácticos para optimizar recursos y manejar el flujo de efectivo de manera efectiva. La charla se centrará en la importancia de construir una cultura empresarial de resiliencia, donde el liderazgo inspirador y la comunicación transparente jueguen un papel clave en la motivación y alineación del equipo. La charla también destacará el papel de la tecnología y la transformación digital en el emprendimiento actual, y cómo estas herramientas pueden potenciar la eficiencia y la adaptabilidad de los negocios."
    },
    {id: 7,
        titulo: " Beyond Office Walls:",
        texto: " Teletrabajo y la Revolución del Espacio Laboral. En esta fascinante conferencia, exploraremos el emocionante mundo del teletrabajo y cómo está transformando radicalmente el espacio laboral tradicional. No es sólo cuestión del teletrabajo, es como nuestros empleados desean disfrutar de una nueva experiencia en la oficina. Romperemos las barreras físicas de las oficinas y abrazaremos una nueva era de flexibilidad y eficiencia. No es sólo una cuestión del teletrabajo, es la nueva flexibilidad. No solo exploraremos el impacto en el presente, sino que miraremos hacia el futuro del espacio laboral. ¿Cómo será el trabajo más allá de las paredes de la oficina? ¿Cómo se redefine el concepto de oficina y horario de trabajo? Estas son solo algunas de las cuestiones provocadoras que abordaremos.",
        textoOtro:"A través de ejemplos inspiradores, los asistentes aprenderán cómo este enfoque revolucionario puede impulsar la innovación, el equilibrio entre la vida laboral y personal, y fomentar una cultura de confianza y autonomía. Javier Krawicki compartirá conocimientos prácticos, consejos y estrategias para superar los desafíos y aprovechar las oportunidades que ofrece la revolución laboral. Adicionalmente en la charla, descubriremos las últimas tendencias y mejores prácticas en teletrabajo, desde cómo implementar y optimizar esta modalidad en tu empresa, hasta cómo aprovechar al máximo las tecnologías y herramientas digitales para una colaboración fluida y productiva."
    },
    {id: 8,
        titulo: " HR 5.0: ",
        texto: "Abrazando la Revolución de las Tendencias en Recursos Humanos: HR Techt Trend: Muchas veces nos ofrecen herramientas, aplicaciones con mucha tecnología y beneficios, pero no entendemos genuinamente “el para que” lo debiera utilizar en mi organización.",
        textoOtro:"A veces nuestros jefes nos solicitan incorporar cierta tecnología, solo por el hecho de no sentirse “fuera del mercado” o porque nos gustó el comercial que nos ofreció la herramienta, pero no logramos entender profundamente el “para que” utilizaría esto. Hay que educar a las personas sobre las diferentes tecnologías con las cuales con convivimos, y cual él es el impacto de estas. Debemos estar preparados para entender cuando nos ofrecen productos o servicios, realmente cómo funcionan y así poder filtrar y/o gestionar mejor, productos nuevos o los ya existentes en nuestra organización."
    },
    {id: 9,
        titulo: "Game On:",
        texto: "IA, Gaming y Metaverso redefiniendo el mercado laboral: No hay dudas que la tecnología nos hace la vida más fácil y la debemos integrar. Pero también debemos ser conscientes de que esto produce cambios en los puestos de trabajo. El objetivo es explorar cómo la inteligencia artificial (IA), la industria de los videojuegos y el metaverso están transformando y redefiniendo el panorama del mercado laboral.",
        textoOtro:"En esta charla, los asistentes aprenderán sobre los avances tecnológicos y la convergencia de estas tres áreas que están dando forma a un nuevo paradigma en el ámbito laboral. Se explorará cómo la IA está revolucionando la automatización de tareas, mejorando la eficiencia y liberando a los profesionales para enfocarse en tareas más estratégicas y creativas. La industria de los videojuegos también desempeña un papel crucial, ya que ha brindado soluciones innovadoras para el desarrollo de habilidades, la gamificación en la formación y el desarrollo de equipos de trabajo. Además, se examinará el concepto emergente del metaverso, un mundo virtual compartido, y cómo está transformando la colaboración, el aprendizaje y la experiencia laboral. Los asistentes descubrirán cómo estas tecnologías están abriendo nuevas oportunidades laborales y cómo pueden prepararse para las demandas cambiantes del mercado laboral. Se presentarán casos de éxito de empresas que ya están utilizando estas tecnologías para mejorar su productividad, eficiencia y creatividad en sus operaciones laborales. También se discutirán los desafíos y consideraciones éticas que surgen con el uso de estas tecnologías, y cómo se pueden abordar de manera responsable en el entorno laboral y la transformación de los puestos de trabajo."
    },
    {id: 10,
        titulo: "CryptoWork: ",
        texto: "Desbloqueando el potencial de las Criptomonedas en el mercado laboral: ¿es una nueva modalidad de pago de salario? ¿Como impacta el mundo crypto en los pagos de los empleados/ contractors? ¿En qué me tengo que preparar? ¿Es solo para los profesionales de tecnología? ¿Aplicará a todos? ¿Aunque personalmente no invierta en Bitcoin u otra criptomoneda, a nivel laboral, tengo que saber algo? Esta charla tiene como objetivo explorar el impacto y las oportunidades que las criptomonedas y la tecnología blockchain ofrecen en el ámbito laboral y empresarial. También los asistentes aprenderán sobre el funcionamiento de las criptomonedas y cómo la tecnología blockchain está transformando la forma en que las transacciones financieras y contractuales se llevan a cabo en el mercado laboral.",
        textoOtro:"Se explorará cómo las criptomonedas pueden ser una solución para superar desafíos en la contratación de talento global, el pago de nóminas y la gestión de beneficios laborales, eliminando intermediarios y reduciendo costos de transacción. En la charla presentaremos casos de éxito y ejemplos concretos de empresas que ya están adoptando criptomonedas en sus procesos laborales, y cómo están obteniendo ventajas competitivas y mejorando la experiencia de sus empleados. También se discutirá cómo las criptomonedas están revolucionando la economía gig, facilitando pagos rápidos y globales a trabajadores independientes y freelancers en todo el mundo."
    },
      
]